# authors:
# David Hernandez Lopez, david.hernandez@uclm.es
import os
import sys

current_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(current_path, '..'))

from pyLibCRSs import CRSsDefines as defs_crs

CRS_DEFAULT = "EPSG:25830+5782"
CRS_PROJECTED_DEFAULT = "EPSG:25830"
CRS_VERTICAL_DEFAULT = "EPSG:5782"
EPSG_STRING_PREFIX = "EPSG:"
QDATE_TO_STRING_FORMAT = "yyyy:MM:dd"
TIME_STRING_FORMAT = "%H:%M:%S.%f"
DATE_STRING_FORMAT = "yyyy:MM:dd"
DATE_TIME_STRING_FORMAT = "%Y%m%d %H:%M:%S"
QDATETIME_TO_STRING_FORMAT_FOR_FILE_NAME = "yyyyMMdd_hhmmss"

PROJECT_DEFINITION_DIALOG_TITLE = "Project Definition"
PROJECT_DEFINITIONS_MANAGEMENT_FIELD_NAME = "Project Definition"
PROJECT_DEFINITIONS_TAG = "ProjectDefinition"
PROJECT_DEFINITIONS_TAG_NAME = "Name"
PROJECT_DEFINITIONS_TAG_TAG = "Tag"
PROJECT_DEFINITIONS_TAG_AUTHOR = "Author"
PROJECT_DEFINITIONS_TAG_CRS = defs_crs.CRS_LABEL
PROJECT_DEFINITIONS_TAG_PROJECTED_CRS = defs_crs.CRS_PROJECTED_LABEL
PROJECT_DEFINITIONS_TAG_VERTICAL_CRS = defs_crs.CRS_VERTICAL_LABEL
PROJECT_DEFINITIONS_TAG_OUTPUT_PATH = "OutputPath"
PROJECT_DEFINITIONS_TAG_DESCRIPTION = "Description"
PROJECT_DEFINITIONS_TAG_START_DATE = "StartDate"
PROJECT_DEFINITIONS_TAG_FINISH_DATE = "FinishDate"

